### ISSUE TITLE
An unexpected error happened

### ISSUE THREAD

**Issue by flopp999** [spectraphilic/grafana-windrose#8] opened 2020-11-18 10:32 UTC
Nice that you made a plugin for Wind roses :)

Grafana 7.3.3 running on Debian buster
InfluxDB 1.8

When I try to get a panel I got below error

any ideas what can be wrong?

![image](https://user-images.githubusercontent.com/21694965/99518953-84cdab00-2991-11eb-882e-d60501e66b19.png)

**Comment by jdavid** [comment] 2020-11-18 10:41
Closing as duplicate of #6

**Closed by jdavid** 2020-11-18 10:41 UTC
